[package]
name = "ts_microservice_generator"
version = "0.1.0"
authors = ["CodewiseTech <dev@codewisetech.biz>"]
edition = "2021"

[dependencies]
clap = "4.5.6"
tera = "1.20.0"

[[bin]]
name = "ts_microservice_generator"
path = "src/main.rs"